// Auto-generated by ROG Falchion Ace HFX Blockly Effect Studio
// Target: ISO C++17 / RAII 0-heap allocation
#pragma once

#include "engine/effect.h"
#include "engine/plugin_interface.h"
#include <cmath>
#include <algorithm>
#include <cstdint>

namespace aura {

class Effect_cs2_health : public Effect {
public:
    Effect_cs2_health() = default;
    virtual ~Effect_cs2_health() = default;

    void Render(uint64_t elapsed_ms, FrameBuffer& out_frame, const Keymap& keymap) override {
        RenderWithContext(elapsed_ms, out_frame, keymap, nullptr);
    }

    void RenderWithContext(uint64_t elapsed_ms, FrameBuffer& out_frame, const Keymap& keymap, const IGsiReader* gsi) {
        double hp = 100.0;
        if (gsi != nullptr) {
            hp = gsi->GetNumber("player.state.health", 100.0);
        }
        const double factor = std::clamp(hp / 100.0, 0.0, 1.0);
        const uint8_t r = static_cast<uint8_t>(std::clamp((1.0 - factor) * 255.0, 0.0, 255.0));
        const uint8_t g = static_cast<uint8_t>(std::clamp(factor * 255.0, 0.0, 255.0));
        out_frame.Fill(r, g, 0);
    }
};

} // namespace aura

extern "C" {
    __declspec(dllexport) uint32_t AuraGetPluginApiVersion() {
        return 0x00010000;
    }

    __declspec(dllexport) const char* AuraGetEffectName() {
        return "cs2_health";
    }

    __declspec(dllexport) aura::Effect* AuraCreateEffect() {
        return new aura::Effect_cs2_health();
    }

    __declspec(dllexport) void AuraDestroyEffect(aura::Effect* effect) {
        delete effect;
    }
}
