#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
test_studio_release_regression.py - Studio Release Native Publish Integration Test Suite

Verifies Scenarios A through I:
  Scenario A: Packaged runtime contains complete Plugin SDK headers.
  Scenario B: Web UI started in an isolated directory without source checkout discovers packaged SDK from LOCALAPPDATA.
  Scenario C: Web UI with CWD in another directory does not mis-resolve include.
  Scenario D: Missing SDK headers return HTTP 400, stage='sdk_missing', exit_code=-6, and diagnostic paths.
  Scenario E: Missing MSVC returns HTTP 400, stage='msvc_missing', exit_code=-1, and draft-saving guidance;
              config/draft saving remains fully functional.
  Scenario F: Release runtime auto-discovery: Unpacked aura_web_ui.exe runs without --sdk-include,
              compiles actual Blockly transpiled C++ (low-health warning) into DLL, and verifies with ctypes WinDLL.
  Scenario G: Explicit --sdk-include path with trailing backslash does not break cl.exe quote parsing.
  Scenario H: Executable in source checkout prioritizes checkout headers over %LOCALAPPDATA% headers.
  Scenario I: Real transpiled effects containing std::min and std::max compile cleanly without MSVC C2589 error.
"""

import os
import sys
import json
import time
import shutil
import ctypes
import zipfile
import tempfile
import unittest
import subprocess
import urllib.request
import urllib.error

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
WEB_UI_EXE = os.path.join(os.environ.get("AURA_BIN_DIR", os.path.join(ROOT_DIR, "build", "Release")), "aura_web_ui.exe")
AURA_EXE = os.path.join(ROOT_DIR, "dist", "Aura.exe")

MINIMAL_PLUGIN_CPP = R"""#include "engine/effect.h"
#include "engine/plugin_interface.h"

namespace aura {
class MinEffect : public Effect {
public:
    MinEffect() = default;
    void Render(uint64_t frame_time_ms, FrameBuffer& fb, const Keymap& keymap) override {
        fb.Fill(0, 128, 255);
    }
};
}

extern "C" {
__declspec(dllexport) uint32_t AuraGetPluginApiVersion(void) {
    return 1;
}

__declspec(dllexport) const char* AuraGetEffectName(void) {
    return "min_effect";
}

__declspec(dllexport) aura::Effect* AuraCreateEffect(void) {
    return new aura::MinEffect();
}

__declspec(dllexport) void AuraDestroyEffect(aura::Effect* effect) {
    delete effect;
}
}
"""

BLOCKLY_GENERATED_CPP = R"""// Auto-generated by ROG Falchion Ace HFX Blockly Effect Studio
// Target: ISO C++17 / RAII 0-heap allocation
#pragma once

#include "engine/effect.h"
#include "engine/plugin_interface.h"
#include <cmath>
#include <algorithm>
#include <cstdint>
#include <string_view>
#include <string>

namespace aura {

inline ColorRGB LerpRGB(const ColorRGB& a, const ColorRGB& b, double t) {
    const double clamped_t = std::clamp(t, 0.0, 1.0);
    return ColorRGB{
        static_cast<uint8_t>(std::clamp(a.r * (1.0 - clamped_t) + b.r * clamped_t, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(a.g * (1.0 - clamped_t) + b.g * clamped_t, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(a.b * (1.0 - clamped_t) + b.b * clamped_t, 0.0, 255.0))
    };
}

inline ColorRGB ScaleBrightness(const ColorRGB& c, double s) {
    const double factor = std::clamp(s, 0.0, 1.0);
    return ColorRGB{
        static_cast<uint8_t>(std::clamp(c.r * factor, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(c.g * factor, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(c.b * factor, 0.0, 255.0))
    };
}

class Effect_test_blockly_rel : public Effect {
public:
    int _pc = 0;
    double _wake = 0;
    uint64_t _last = 0;
    bool _initialized = false;
    FrameBuffer _frame{};
    const KeyInfo* _keys[68]{};
    int _indices[1]{};
    int _limits[1]{};

    Effect_test_blockly_rel() = default;
    virtual ~Effect_test_blockly_rel() = default;

    void Render(uint64_t elapsed_ms, FrameBuffer& out_frame, const Keymap& keymap) override {
        RenderInternal(elapsed_ms, out_frame, keymap, nullptr);
    }

    void RenderWithContext(const EffectContext& ctx, FrameBuffer& out_frame) override {
        RenderInternal(ctx.elapsed_ms, out_frame, ctx.keymap, ctx.gsi);
    }

    void RenderInternal(uint64_t elapsed_ms, FrameBuffer& out_frame, const Keymap& keymap, const IGsiReader* gsi) {
        if (!_initialized || elapsed_ms < _last) {
            static constexpr const char* _key_names[68] = {
                "ESC", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "=", "BACKSPACE", "INS",
                "TAB", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "[", "]", "\\", "DEL",
                "CAPS", "A", "S", "D", "F", "G", "H", "J", "K", "L", ";", "'", "ENTER", "PGUP",
                "L_SHIFT", "Z", "X", "C", "V", "B", "N", "M", ",", ".", "/", "R_SHIFT", "UP", "PGDN",
                "L_CTRL", "L_WIN", "L_ALT", "SPACE", "R_ALT", "FN", "COPILOT", "LEFT", "DOWN", "RIGHT"
            };
            for (size_t i = 0; i < 68; ++i) {
                auto it = keymap.GetAllKeys().find(_key_names[i]);
                _keys[i] = it == keymap.GetAllKeys().end() ? nullptr : &it->second;
            }
            _initialized = true; _pc = 0; _wake = 0; _frame.Clear();
        }
        _last = elapsed_ms;
        if (elapsed_ms < _wake) { out_frame = _frame; return; }
        _frame.Fill(100, 200, 255);
        out_frame = _frame;
    }
};

} // namespace aura

extern "C" {
    __declspec(dllexport) uint32_t AuraGetPluginApiVersion() {
        return 0x00010000;
    }

    __declspec(dllexport) const char* AuraGetEffectName() {
        return "test_blockly_rel";
    }

    __declspec(dllexport) aura::Effect* AuraCreateEffect() {
        return new aura::Effect_test_blockly_rel();
    }

    __declspec(dllexport) void AuraDestroyEffect(aura::Effect* effect) {
        delete effect;
    }
}
"""

# Real CppTranspiler output for "CS2 低血量警戒 (Health Warning)" template (template_low_health_warning).
# Emits std::max(100.0, static_cast<double>(0.8) * 1000.0) within color_cycle lambda.
LOW_HEALTH_TEMPLATE_CPP = R"""// Auto-generated by ROG Falchion Ace HFX Blockly Effect Studio
// Target: ISO C++17 / RAII 0-heap allocation
#pragma once

#include "engine/effect.h"
#include "engine/plugin_interface.h"
#include <cmath>
#include <algorithm>
#include <cstdint>
#include <string_view>
#include <string>

namespace aura {

inline ColorRGB LerpRGB(const ColorRGB& a, const ColorRGB& b, double t) {
    const double clamped_t = std::clamp(t, 0.0, 1.0);
    return ColorRGB{
        static_cast<uint8_t>(std::clamp(a.r * (1.0 - clamped_t) + b.r * clamped_t, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(a.g * (1.0 - clamped_t) + b.g * clamped_t, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(a.b * (1.0 - clamped_t) + b.b * clamped_t, 0.0, 255.0))
    };
}

inline ColorRGB ScaleBrightness(const ColorRGB& c, double s) {
    const double factor = std::clamp(s, 0.0, 1.0);
    return ColorRGB{
        static_cast<uint8_t>(std::clamp(c.r * factor, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(c.g * factor, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(c.b * factor, 0.0, 255.0))
    };
}

class Effect_template_low_health_warning : public Effect {
public:
    int _pc = 3;
    double _wake = 0;
    uint64_t _last = 0;
    bool _initialized = false;
    FrameBuffer _frame{};
    const KeyInfo* _keys[68]{};
    int _indices[1]{};
    int _limits[1]{};
    
    Effect_template_low_health_warning() = default;
    virtual ~Effect_template_low_health_warning() = default;

    void Render(uint64_t elapsed_ms, FrameBuffer& out_frame, const Keymap& keymap) override {
        RenderInternal(elapsed_ms, out_frame, keymap, nullptr);
    }

    void RenderWithContext(const EffectContext& ctx, FrameBuffer& out_frame) override {
        RenderInternal(ctx.elapsed_ms, out_frame, ctx.keymap, ctx.gsi);
    }

    void RenderInternal(uint64_t elapsed_ms, FrameBuffer& out_frame, const Keymap& keymap, const IGsiReader* gsi) {
        if (!_initialized || elapsed_ms < _last) {
            static constexpr const char* _key_names[68] = {
                "ESC", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "=", "BACKSPACE", "INS",
                "TAB", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "[", "]", "\\", "DEL",
                "CAPS", "A", "S", "D", "F", "G", "H", "J", "K", "L", ";", "'", "ENTER", "PGUP",
                "L_SHIFT", "Z", "X", "C", "V", "B", "N", "M", ",", ".", "/", "R_SHIFT", "UP", "PGDN",
                "L_CTRL", "L_WIN", "L_ALT", "SPACE", "R_ALT", "FN", "COPILOT", "LEFT", "DOWN", "RIGHT"
            };
            for (size_t i = 0; i < 68; ++i) {
                auto it = keymap.GetAllKeys().find(_key_names[i]);
                _keys[i] = it == keymap.GetAllKeys().end() ? nullptr : &it->second;
            }
            _initialized = true; _pc = 3; _wake = 0; _frame.Clear();
        }
        _last = elapsed_ms;
        if (elapsed_ms < _wake) { out_frame = _frame; return; }
        const KeyInfo info{};
        for (int _budget = 0; _budget < 4096; ++_budget) {
            switch (_pc) {
                case 0: { _pc = 3; out_frame = _frame; return; }
                case 1: {
                    _frame.Fill(ColorRGB{static_cast<uint8_t>(std::clamp(static_cast<double>(0), 0.0, 255.0)),
                                         static_cast<uint8_t>(std::clamp(static_cast<double>(120), 0.0, 255.0)),
                                         static_cast<uint8_t>(std::clamp(static_cast<double>(255), 0.0, 255.0))});
                    _pc = 0; break;
                }
                case 2: {
                    _frame.Fill([&]() -> ColorRGB {
                        const double _p_ms = std::max(100.0, static_cast<double>(0.8) * 1000.0);
                        const double _phase = std::fmod(static_cast<double>(elapsed_ms), _p_ms) / _p_ms;
                        const double _ratio = 0.5 - 0.5 * std::cos(_phase * 6.283185307179586);
                        return LerpRGB(ColorRGB{255, 0, 0}, ColorRGB{0, 0, 0}, _ratio);
                    }());
                    _pc = 0; break;
                }
                case 3: {
                    _pc = (((gsi ? gsi->GetNumber("player.state.health", 100.0) : 100.0) < 25)) ? 2 : 1;
                    break;
                }
            }
        }
        out_frame = _frame;
    }
};

} // namespace aura

extern "C" {
    __declspec(dllexport) uint32_t AuraGetPluginApiVersion() {
        return 0x00010000;
    }

    __declspec(dllexport) const char* AuraGetEffectName() {
        return "template_low_health_warning";
    }

    __declspec(dllexport) aura::Effect* AuraCreateEffect() {
        return new aura::Effect_template_low_health_warning();
    }

    __declspec(dllexport) void AuraDestroyEffect(aura::Effect* effect) {
        delete effect;
    }
}
"""

# Real CppTranspiler output combining controls_repeat_ext and key_ripple_effect.
# Emits BOTH std::min(...) and std::max(...) to ensure neither is corrupted by windows.h macros.
REPEAT_RIPPLE_TEMPLATE_CPP = R"""// Auto-generated by ROG Falchion Ace HFX Blockly Effect Studio
// Target: ISO C++17 / RAII 0-heap allocation
#pragma once

#include "engine/effect.h"
#include "engine/plugin_interface.h"
#include <cmath>
#include <algorithm>
#include <cstdint>
#include <string_view>
#include <string>

namespace aura {

inline ColorRGB ScaleBrightness(const ColorRGB& c, double s) {
    const double factor = std::clamp(s, 0.0, 1.0);
    return ColorRGB{
        static_cast<uint8_t>(std::clamp(c.r * factor, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(c.g * factor, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(c.b * factor, 0.0, 255.0))
    };
}

class Effect_test_repeat_ripple : public Effect {
public:
    int _pc = 1;
    double _wake = 0;
    uint64_t _last = 0;
    bool _initialized = false;
    FrameBuffer _frame{};
    const KeyInfo* _keys[68]{};
    int _indices[1]{};
    int _limits[1]{};

    Effect_test_repeat_ripple() = default;
    virtual ~Effect_test_repeat_ripple() = default;

    void Render(uint64_t elapsed_ms, FrameBuffer& out_frame, const Keymap& keymap) override {
        RenderInternal(elapsed_ms, out_frame, keymap, nullptr);
    }

    void RenderWithContext(const EffectContext& ctx, FrameBuffer& out_frame) override {
        RenderInternal(ctx.elapsed_ms, out_frame, ctx.keymap, ctx.gsi);
    }

    void RenderInternal(uint64_t elapsed_ms, FrameBuffer& out_frame, const Keymap& keymap, const IGsiReader* gsi) {
        if (!_initialized || elapsed_ms < _last) {
            static constexpr const char* _key_names[68] = {
                "ESC", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "=", "BACKSPACE", "INS",
                "TAB", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "[", "]", "\\", "DEL",
                "CAPS", "A", "S", "D", "F", "G", "H", "J", "K", "L", ";", "'", "ENTER", "PGUP",
                "L_SHIFT", "Z", "X", "C", "V", "B", "N", "M", ",", ".", "/", "R_SHIFT", "UP", "PGDN",
                "L_CTRL", "L_WIN", "L_ALT", "SPACE", "R_ALT", "FN", "COPILOT", "LEFT", "DOWN", "RIGHT"
            };
            for (size_t i = 0; i < 68; ++i) {
                auto it = keymap.GetAllKeys().find(_key_names[i]);
                _keys[i] = it == keymap.GetAllKeys().end() ? nullptr : &it->second;
            }
            _initialized = true; _pc = 1; _wake = 0; _frame.Clear();
        }
        _last = elapsed_ms;
        if (elapsed_ms < _wake) { out_frame = _frame; return; }
        const KeyInfo info{};
        for (int _budget = 0; _budget < 4096; ++_budget) {
            switch (_pc) {
                case 0: { _pc = 1; out_frame = _frame; return; }
                case 1: {
                    for (int _rpt = 0; _rpt < std::min(1000, std::max(0, static_cast<int>(3))); ++_rpt) {
                        double _cx = 7.5, _cy = 3.0;
                        auto _it = keymap.GetAllKeys().find("SPACE");
                        if (_it != keymap.GetAllKeys().end()) { _cx = _it->second.physical_x; _cy = _it->second.physical_y; }
                        const ColorRGB _base_col = ColorRGB{255, 200, 0};
                        const double _sp = 5.0;
                        for (size_t _i = 0; _i < 68; ++_i) {
                            if (!_keys[_i]) continue;
                            const double _dist = std::hypot(_keys[_i]->physical_x - _cx, _keys[_i]->physical_y - _cy);
                            const double _phase = std::fmod(std::fmod(_dist - (static_cast<double>(elapsed_ms) / 1000.0) * _sp, 4.0) + 4.0, 4.0);
                            const double _wave = std::max(0.0, 1.0 - std::fabs(_phase - 1.0));
                            _frame.SetKey(_i, ScaleBrightness(_base_col, _wave));
                        }
                    }
                    _pc = 0;
                    break;
                }
            }
        }
        out_frame = _frame;
    }
};

} // namespace aura

extern "C" {
    __declspec(dllexport) uint32_t AuraGetPluginApiVersion() {
        return 0x00010000;
    }

    __declspec(dllexport) const char* AuraGetEffectName() {
        return "test_repeat_ripple";
    }

    __declspec(dllexport) aura::Effect* AuraCreateEffect() {
        return new aura::Effect_test_repeat_ripple();
    }

    __declspec(dllexport) void AuraDestroyEffect(aura::Effect* effect) {
        delete effect;
    }
}
"""

def fetch_json(url, method="GET", body=None, headers=None, timeout=5.0):
    req_headers = {"User-Agent": "AuraStudioTest/1.0"}
    if headers:
        req_headers.update(headers)
    req_data = None
    if body is not None:
        if isinstance(body, (dict, list)):
            req_data = json.dumps(body).encode("utf-8")
            req_headers["Content-Type"] = "application/json"
        elif isinstance(body, (str, bytes)):
            req_data = body if isinstance(body, bytes) else body.encode("utf-8")
    req = urllib.request.Request(url, data=req_data, headers=req_headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            data = resp.read().decode("utf-8")
            return resp.status, json.loads(data) if data else {}
    except urllib.error.HTTPError as e:
        data = e.read().decode("utf-8", errors="replace")
        try:
            parsed = json.loads(data)
        except Exception:
            parsed = {"raw": data}
        return e.code, parsed

def wait_for_server(port, timeout=5.0):
    start = time.time()
    while time.time() - start < timeout:
        try:
            status, data = fetch_json(f"http://127.0.0.1:{port}/api/status", timeout=0.5)
            if status == 200 and data.get("status") == "ok":
                return True
        except Exception:
            pass
        time.sleep(0.1)
    return False

def terminate_proc(proc):
    if proc:
        if proc.poll() is None:
            proc.terminate()
            try:
                proc.wait(timeout=3.0)
            except subprocess.TimeoutExpired:
                proc.kill()
                proc.wait(timeout=2.0)
        if proc.stdout:
            try:
                proc.stdout.close()
            except Exception:
                pass
        if proc.stderr:
            try:
                proc.stderr.close()
            except Exception:
                pass

class TestStudioReleaseRegression(unittest.TestCase):
    def setUp(self):
        self.tmp_dir = tempfile.mkdtemp(prefix="aura_test_regression_")
        self.sandbox_appdata = os.path.join(self.tmp_dir, "appdata")
        os.makedirs(self.sandbox_appdata, exist_ok=True)
        self.env = os.environ.copy()
        self.env["LOCALAPPDATA"] = self.sandbox_appdata
        self.env["TEMP"] = self.tmp_dir
        self.env["TMP"] = self.tmp_dir

    def tearDown(self):
        shutil.rmtree(self.tmp_dir, ignore_errors=True)

    def test_scenario_a_packaged_runtime_contains_complete_sdk(self):
        """Scenario A: Verify dist/Aura.exe extracts complete Plugin SDK headers into %LOCALAPPDATA%/Aura/runtime/include."""
        self.assertTrue(os.path.isfile(AURA_EXE), f"dist/Aura.exe does not exist at {AURA_EXE}")
        
        # Run Aura.exe --help in sandbox to trigger extraction
        res = subprocess.run([AURA_EXE, "--help"], cwd=self.tmp_dir, env=self.env, capture_output=True, encoding="utf-8", errors="replace")
        self.assertEqual(res.returncode, 0)
        
        extracted_sdk = os.path.join(self.sandbox_appdata, "Aura", "runtime", "include")
        expected_headers = [
            os.path.join(extracted_sdk, "engine", "effect.h"),
            os.path.join(extracted_sdk, "engine", "plugin_interface.h"),
            os.path.join(extracted_sdk, "aura", "aura_types.h"),
            os.path.join(extracted_sdk, "aura", "keymap.h"),
        ]
        for header_path in expected_headers:
            self.assertTrue(os.path.isfile(header_path), f"Extracted header not found: {header_path}")
            self.assertGreater(os.path.getsize(header_path), 500, f"Extracted header is unexpectedly small: {header_path}")

    def test_scenario_b_web_ui_discovers_packaged_sdk_in_isolated_directory(self):
        """Scenario B: Web UI in clean directory without checkout discovers packaged SDK from LOCALAPPDATA."""
        # 1. First unpack SDK via launcher into sandbox LOCALAPPDATA
        subprocess.run([AURA_EXE, "--help"], cwd=self.tmp_dir, env=self.env, capture_output=True, encoding="utf-8", errors="replace")
        extracted_sdk = os.path.join(self.sandbox_appdata, "Aura", "runtime", "include")
        self.assertTrue(os.path.isfile(os.path.join(extracted_sdk, "engine", "effect.h")))

        # 2. Run aura_web_ui.exe from an isolated work directory without source checkout
        isolated_work = os.path.join(self.tmp_dir, "clean_work")
        os.makedirs(isolated_work, exist_ok=True)
        isolated_web_exe = os.path.join(isolated_work, "aura_web_ui.exe")
        shutil.copy2(WEB_UI_EXE, isolated_web_exe)

        port = 29810
        proc = subprocess.Popen([isolated_web_exe, "--port", str(port)],
                                cwd=isolated_work, env=self.env,
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        try:
            self.assertTrue(wait_for_server(port), "Web server failed to start")
            status, data = fetch_json(f"http://127.0.0.1:{port}/api/status")
            self.assertEqual(status, 200)
            self.assertTrue(data.get("sdk_headers_found"), "Expected sdk_headers_found to be true from LOCALAPPDATA")
            self.assertIn("Aura", data.get("sdk_include_dir", ""))

            # Compile test plugin to verify compilation works using auto-discovered LOCALAPPDATA SDK
            status, comp = fetch_json(f"http://127.0.0.1:{port}/api/compile_effect", method="POST",
                                      body={"name": "test_scen_b", "code": MINIMAL_PLUGIN_CPP})
            self.assertEqual(status, 200, f"Compilation in clean directory failed: {comp}")
            self.assertTrue(comp.get("success"))
        finally:
            terminate_proc(proc)

    def test_scenario_c_cwd_in_foreign_directory_does_not_pollute_include(self):
        """Scenario C: When CWD contains a dummy/broken include/ directory, Web UI does not use it."""
        # Setup dummy foreign checkout with broken effect.h in CWD
        foreign_cwd = os.path.join(self.tmp_dir, "foreign_checkout")
        foreign_inc = os.path.join(foreign_cwd, "include", "engine")
        os.makedirs(foreign_inc, exist_ok=True)
        with open(os.path.join(foreign_inc, "effect.h"), "w", encoding="utf-8") as f:
            f.write("// BROKEN FOREIGN HEADER THAT MUST NEVER BE INCLUDED\n#error FOREIGN_INCLUDE_USED\n")
        
        # Also copy real SDK to an explicit path
        real_sdk = os.path.join(self.tmp_dir, "real_sdk")
        for sub, fn in [("engine", "effect.h"), ("engine", "plugin_interface.h"), ("aura", "aura_types.h"), ("aura", "keymap.h")]:
            src = os.path.join(ROOT_DIR, "include", sub, fn)
            dst = os.path.join(real_sdk, sub, fn)
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(src, dst)

        port = 29811
        proc = subprocess.Popen([WEB_UI_EXE, "--port", str(port), "--sdk-include", real_sdk],
                                cwd=foreign_cwd, env=self.env,
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        try:
            self.assertTrue(wait_for_server(port), "Web server failed to start")
            status, data = fetch_json(f"http://127.0.0.1:{port}/api/status")
            self.assertEqual(status, 200)
            self.assertTrue(data.get("sdk_headers_found"))
            # Normalized paths comparison
            self.assertEqual(os.path.normpath(data.get("sdk_include_dir")), os.path.normpath(real_sdk))

            # Compile test plugin to ensure FOREIGN_INCLUDE_USED was NOT triggered
            status, comp = fetch_json(f"http://127.0.0.1:{port}/api/compile_effect", method="POST",
                                      body={"name": "test_cwd_iso", "code": MINIMAL_PLUGIN_CPP})
            self.assertEqual(status, 200, f"Compilation failed: {comp}")
            self.assertTrue(comp.get("success"))
        finally:
            terminate_proc(proc)

    def test_scenario_d_missing_sdk_headers_diagnostic_error(self):
        """Scenario D: Missing SDK headers return HTTP 400, stage='sdk_missing', exit_code=-6, and checked paths."""
        empty_sdk_dir = os.path.join(self.tmp_dir, "empty_sdk")
        os.makedirs(empty_sdk_dir, exist_ok=True)

        # Force missing SDK for isolation test
        env_no_sdk = self.env.copy()
        env_no_sdk["AURA_TEST_FORCE_NO_SDK"] = "1"

        port = 29812
        proc = subprocess.Popen([WEB_UI_EXE, "--port", str(port), "--sdk-include", empty_sdk_dir],
                                cwd=self.tmp_dir, env=env_no_sdk,
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        try:
            self.assertTrue(wait_for_server(port), "Web server failed to start")
            status, st = fetch_json(f"http://127.0.0.1:{port}/api/status")
            self.assertEqual(status, 200)
            self.assertFalse(st.get("sdk_headers_found"))
            self.assertFalse(st.get("studio_publish_ready"))

            # Attempt to compile
            status, comp = fetch_json(f"http://127.0.0.1:{port}/api/compile_effect", method="POST",
                                      body={"name": "test_missing_sdk", "code": MINIMAL_PLUGIN_CPP})
            self.assertEqual(status, 400)
            self.assertFalse(comp.get("success"))
            self.assertEqual(comp.get("stage"), "sdk_missing")
            self.assertEqual(comp.get("exit_code"), -6)
            self.assertIn("SDK", comp.get("message", ""))
            # Check that checked paths and missing files are reported in compiler_output/log
            log = comp.get("compiler_output", "")
            self.assertTrue("effect.h" in log or "plugin_interface.h" in log)
        finally:
            terminate_proc(proc)

    def test_scenario_e_missing_msvc_diagnostic_and_draft_preservation(self):
        """Scenario E: When MSVC is missing, returns stage='msvc_missing', exit_code=-1, but draft saving works."""
        sdk_dir = os.path.join(ROOT_DIR, "include")
        env_no_msvc = self.env.copy()
        env_no_msvc["AURA_TEST_FORCE_NO_MSVC"] = "1"

        port = 29813
        proc = subprocess.Popen([WEB_UI_EXE, "--port", str(port), "--sdk-include", sdk_dir],
                                cwd=self.tmp_dir, env=env_no_msvc,
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        try:
            self.assertTrue(wait_for_server(port), "Web server failed to start")
            status, st = fetch_json(f"http://127.0.0.1:{port}/api/status")
            self.assertEqual(status, 200)
            self.assertTrue(st.get("sdk_headers_found"))
            self.assertFalse(st.get("msvc_found"))
            self.assertFalse(st.get("studio_publish_ready"))

            # 1. Attempt to compile native effect -> Should fail with msvc_missing and clear advice
            status, comp = fetch_json(f"http://127.0.0.1:{port}/api/compile_effect", method="POST",
                                      body={"name": "test_no_msvc", "code": MINIMAL_PLUGIN_CPP})
            self.assertEqual(status, 400)
            self.assertFalse(comp.get("success"))
            self.assertEqual(comp.get("stage"), "msvc_missing")
            self.assertEqual(comp.get("exit_code"), -1)
            msg = comp.get("message", "")
            self.assertIn("C++ Desktop workload", msg)
            self.assertIn("保存草稿", msg)

            # 2. Verify draft saving / config saving remains FULLY OPERATIONAL without MSVC!
            draft_cfg = {
                "profiles": {},
                "blockly_effects": {
                    "my_draft_effect": {
                        "name": "my_draft_effect",
                        "version": 2,
                        "blockly_json": {"blocks": {"languageVersion": 0, "blocks": []}}
                    }
                }
            }
            # Fetch current ETag for optimistic concurrency (mandatory If-Match)
            req_get = urllib.request.Request(f"http://127.0.0.1:{port}/api/config")
            with urllib.request.urlopen(req_get, timeout=5.0) as resp:
                etag = resp.headers.get("ETag")
                current_cfg = json.load(resp)
            current_cfg["blockly_effects"] = draft_cfg["blockly_effects"]
            draft_cfg = current_cfg
            status, save_res = fetch_json(f"http://127.0.0.1:{port}/api/config", method="POST", body=draft_cfg, headers={"If-Match": etag})
            self.assertEqual(status, 200)
            self.assertEqual(save_res.get("status"), "ok")

            # Read back saved config
            status, read_cfg = fetch_json(f"http://127.0.0.1:{port}/api/config")
            self.assertEqual(status, 200)
            self.assertIn("my_draft_effect", read_cfg.get("blockly_effects", {}))
        finally:
            terminate_proc(proc)

    def test_scenario_f_valid_isolated_compilation_and_dll_execution(self):
        """Scenario F: Run the unpacked runtime aura_web_ui.exe directly without --sdk-include,
        compile actual Blockly transpiled C++, and verify DLL with ctypes."""
        # 1. Extract SDK and runtime binaries from Aura.exe into sandbox
        res = subprocess.run([AURA_EXE, "--help"], cwd=self.tmp_dir, env=self.env, capture_output=True)
        self.assertEqual(res.returncode, 0)
        unpacked_web_ui = os.path.join(self.sandbox_appdata, "Aura", "runtime", "aura_web_ui.exe")
        self.assertTrue(os.path.isfile(unpacked_web_ui), f"Unpacked web ui not found at {unpacked_web_ui}")
        
        # 2. Run unpacked aura_web_ui.exe directly WITHOUT --sdk-include in an isolated execution directory
        isolated_dir = os.path.join(self.tmp_dir, "isolated_exec")
        os.makedirs(isolated_dir, exist_ok=True)
        port = 29814
        proc = subprocess.Popen([unpacked_web_ui, "--port", str(port)],
                                cwd=isolated_dir, env=self.env,
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        try:
            self.assertTrue(wait_for_server(port), "Web server failed to start")
            status, st = fetch_json(f"http://127.0.0.1:{port}/api/status")
            self.assertEqual(status, 200)
            self.assertTrue(st.get("studio_publish_ready"), f"Studio should be ready: {st}")
            self.assertTrue(st.get("sdk_headers_found"))
            self.assertTrue(st.get("msvc_found"))

            # 3. Post compilation request for real low health template transpiled C++ code (contains std::max)
            plugin_name = "template_low_health_warning"
            status, comp = fetch_json(f"http://127.0.0.1:{port}/api/compile_effect", method="POST",
                                      body={"name": plugin_name, "code": LOW_HEALTH_TEMPLATE_CPP})
            self.assertEqual(status, 200, f"Compilation failed: {comp}")
            self.assertTrue(comp.get("success"))
            compiler_out = comp.get("compiler_output", "")
            self.assertNotIn("C2589", compiler_out, f"Found C2589 error in output: {compiler_out}")
            
            # 4. Verify DLL on disk in isolated_dir/plugins/effect_template_low_health_warning.dll
            dll_path = os.path.join(isolated_dir, "plugins", f"effect_{plugin_name}.dll")
            self.assertTrue(os.path.isfile(dll_path), f"DLL does not exist at {dll_path}")

            # 5. Dynamically load DLL with ctypes and call exports
            lib = ctypes.WinDLL(dll_path)
            
            # Check AuraGetPluginApiVersion -> Blockly CppTranspiler emits 0x00010000
            self.assertTrue(hasattr(lib, "AuraGetPluginApiVersion"))
            lib.AuraGetPluginApiVersion.restype = ctypes.c_uint32
            api_ver = lib.AuraGetPluginApiVersion()
            self.assertEqual(api_ver, 0x00010000, f"Expected API version 0x00010000, got 0x{api_ver:08x}")

            # Check AuraGetEffectName
            self.assertTrue(hasattr(lib, "AuraGetEffectName"))
            lib.AuraGetEffectName.restype = ctypes.c_char_p
            eff_name = lib.AuraGetEffectName().decode("utf-8")
            self.assertEqual(eff_name, "template_low_health_warning")

            # Check AuraCreateEffect & AuraDestroyEffect
            self.assertTrue(hasattr(lib, "AuraCreateEffect"))
            self.assertTrue(hasattr(lib, "AuraDestroyEffect"))
            lib.AuraCreateEffect.restype = ctypes.c_void_p
            lib.AuraDestroyEffect.argtypes = [ctypes.c_void_p]
            lib.AuraDestroyEffect.restype = None

            effect_ptr = lib.AuraCreateEffect()
            self.assertIsNotNone(effect_ptr)
            self.assertNotEqual(effect_ptr, 0)
            
            # Destroy cleanly
            lib.AuraDestroyEffect(effect_ptr)
        finally:
            terminate_proc(proc)

    def test_scenario_g_trailing_slash_in_sdk_include_does_not_break_cl(self):
        """Scenario G: Passing --sdk-include with trailing slash/backslash does not escape cl.exe quotes."""
        sdk_with_slash = os.path.join(ROOT_DIR, "include") + os.sep
        port = 29815
        proc = subprocess.Popen([WEB_UI_EXE, "--port", str(port), "--sdk-include", sdk_with_slash],
                                cwd=self.tmp_dir, env=self.env,
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        try:
            self.assertTrue(wait_for_server(port), "Web server failed to start")
            status, comp = fetch_json(f"http://127.0.0.1:{port}/api/compile_effect", method="POST",
                                      body={"name": "test_slash", "code": MINIMAL_PLUGIN_CPP})
            self.assertEqual(status, 200, f"Compilation failed with trailing slash in --sdk-include: {comp}")
            self.assertTrue(comp.get("success"))
        finally:
            terminate_proc(proc)

    def test_scenario_h_dev_checkout_prioritized_over_localappdata(self):
        """Scenario H: aura_web_ui.exe in a source checkout uses checkout headers even if %LOCALAPPDATA% has runtime SDK."""
        # Setup dummy header in LOCALAPPDATA
        dummy_runtime_inc = os.path.join(self.sandbox_appdata, "Aura", "runtime", "include")
        os.makedirs(os.path.join(dummy_runtime_inc, "engine"), exist_ok=True)
        os.makedirs(os.path.join(dummy_runtime_inc, "aura"), exist_ok=True)
        for sub, fn in [("engine", "effect.h"), ("engine", "plugin_interface.h"), ("aura", "aura_types.h"), ("aura", "keymap.h")]:
            with open(os.path.join(dummy_runtime_inc, sub, fn), "w", encoding="utf-8") as f:
                f.write("// DUMMY RUNTIME HEADER\n")

        port = 29816
        # Run WEB_UI_EXE which resides in ROOT_DIR/build/Release (part of source checkout)
        proc = subprocess.Popen([WEB_UI_EXE, "--port", str(port)],
                                cwd=ROOT_DIR, env=self.env,
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        try:
            self.assertTrue(wait_for_server(port), "Web server failed to start")
            status, st = fetch_json(f"http://127.0.0.1:{port}/api/status")
            self.assertEqual(status, 200)
            self.assertTrue(st.get("sdk_headers_found"))
            sdk_dir = os.path.normpath(st.get("sdk_include_dir", ""))
            expected_repo_inc = os.path.normpath(os.path.join(ROOT_DIR, "include"))
            self.assertEqual(sdk_dir, expected_repo_inc,
                             f"Expected source checkout include '{expected_repo_inc}', but got '{sdk_dir}'")
        finally:
            terminate_proc(proc)

    def test_scenario_i_real_transpiled_min_max_effects_compile_cleanly(self):
        """Scenario I: Verify real CppTranspiler effects containing std::min and std::max
        (specifically low-health warning template and repeat/ripple effect) compile cleanly
        without MSVC C2589 macro pollution errors and produce valid loadable DLLs."""
        port = 29817
        proc = subprocess.Popen([WEB_UI_EXE, "--port", str(port)],
                                cwd=self.tmp_dir, env=self.env,
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        try:
            self.assertTrue(wait_for_server(port), "Web server failed to start")

            # 1. Compile low-health warning template (contains std::max)
            status, comp = fetch_json(f"http://127.0.0.1:{port}/api/compile_effect", method="POST",
                                      body={"name": "test_i_low_health", "code": LOW_HEALTH_TEMPLATE_CPP})
            self.assertEqual(status, 200, f"Low-health warning compilation failed: {comp}")
            self.assertTrue(comp.get("success"), f"Expected success: true, got {comp}")
            compiler_out = comp.get("compiler_output", "")
            self.assertNotIn("C2589", compiler_out, f"Found C2589 error in output: {compiler_out}")

            dll_lh = os.path.join(self.tmp_dir, "plugins", "effect_test_i_low_health.dll")
            self.assertTrue(os.path.isfile(dll_lh), f"DLL not found: {dll_lh}")
            lib_lh = ctypes.WinDLL(dll_lh)
            lib_lh.AuraGetPluginApiVersion.restype = ctypes.c_uint32
            self.assertEqual(lib_lh.AuraGetPluginApiVersion(), 0x00010000)
            lib_lh.AuraCreateEffect.restype = ctypes.c_void_p
            lib_lh.AuraDestroyEffect.argtypes = [ctypes.c_void_p]
            lib_lh.AuraDestroyEffect.restype = None
            lh_obj = lib_lh.AuraCreateEffect()
            self.assertIsNotNone(lh_obj)
            lib_lh.AuraDestroyEffect(lh_obj)

            # 2. Compile repeat/ripple effect (contains both std::min and std::max)
            status2, comp2 = fetch_json(f"http://127.0.0.1:{port}/api/compile_effect", method="POST",
                                        body={"name": "test_i_repeat_ripple", "code": REPEAT_RIPPLE_TEMPLATE_CPP})
            self.assertEqual(status2, 200, f"Repeat/ripple compilation failed: {comp2}")
            self.assertTrue(comp2.get("success"), f"Expected success: true, got {comp2}")
            compiler_out2 = comp2.get("compiler_output", "")
            self.assertNotIn("C2589", compiler_out2, f"Found C2589 error in output: {compiler_out2}")

            dll_rr = os.path.join(self.tmp_dir, "plugins", "effect_test_i_repeat_ripple.dll")
            self.assertTrue(os.path.isfile(dll_rr), f"DLL not found: {dll_rr}")
            lib_rr = ctypes.WinDLL(dll_rr)
            lib_rr.AuraGetPluginApiVersion.restype = ctypes.c_uint32
            self.assertEqual(lib_rr.AuraGetPluginApiVersion(), 0x00010000)
            lib_rr.AuraCreateEffect.restype = ctypes.c_void_p
            lib_rr.AuraDestroyEffect.argtypes = [ctypes.c_void_p]
            lib_rr.AuraDestroyEffect.restype = None
            rr_obj = lib_rr.AuraCreateEffect()
            self.assertIsNotNone(rr_obj)
            lib_rr.AuraDestroyEffect(rr_obj)
        finally:
            terminate_proc(proc)

if __name__ == "__main__":
    unittest.main(verbosity=2)
