// Auto-generated by ROG Falchion Ace HFX Blockly Effect Studio
// Target: ISO C++17 / RAII 0-heap allocation
#pragma once

#include "engine/effect.h"
#include "engine/plugin_interface.h"
#include <cmath>
#include <algorithm>
#include <cstdint>
#include <string_view>
#include <string>

namespace aura {

inline ColorRGB LerpRGB(const ColorRGB& a, const ColorRGB& b, double t) {
    const double clamped_t = std::clamp(t, 0.0, 1.0);
    return ColorRGB{
        static_cast<uint8_t>(std::clamp(a.r * (1.0 - clamped_t) + b.r * clamped_t, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(a.g * (1.0 - clamped_t) + b.g * clamped_t, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(a.b * (1.0 - clamped_t) + b.b * clamped_t, 0.0, 255.0))
    };
}

inline ColorRGB ScaleBrightness(const ColorRGB& c, double s) {
    const double factor = std::clamp(s, 0.0, 1.0);
    return ColorRGB{
        static_cast<uint8_t>(std::clamp(c.r * factor, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(c.g * factor, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(c.b * factor, 0.0, 255.0))
    };
}

class Effect_studio_cs2_health_d6c40fe81cb54d87a84a : public Effect {
public:
    int _pc = 3;
    double _wake = 0;
    uint64_t _last = 0;
    bool _initialized = false;
    FrameBuffer _frame{};
    const KeyInfo* _keys[68]{};
    int _indices[1]{};
    int _limits[1]{};
    
    Effect_studio_cs2_health_d6c40fe81cb54d87a84a() = default;
    virtual ~Effect_studio_cs2_health_d6c40fe81cb54d87a84a() = default;

    void Render(uint64_t elapsed_ms, FrameBuffer& out_frame, const Keymap& keymap) override {
        RenderInternal(elapsed_ms, out_frame, keymap, nullptr);
    }

    void RenderWithContext(const EffectContext& ctx, FrameBuffer& out_frame) override {
        RenderInternal(ctx.elapsed_ms, out_frame, ctx.keymap, ctx.gsi);
    }

    void RenderInternal(uint64_t elapsed_ms, FrameBuffer& out_frame, const Keymap& keymap, const IGsiReader* gsi) {

        if (!_initialized || elapsed_ms < _last) {
            static constexpr const char* _key_names[68] = { "ESC", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "=", "BACKSPACE", "INS", "TAB", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "[", "]", "\\", "DEL", "CAPS", "A", "S", "D", "F", "G", "H", "J", "K", "L", ";", "'", "ENTER", "PGUP", "L_SHIFT", "Z", "X", "C", "V", "B", "N", "M", ",", ".", "/", "R_SHIFT", "UP", "PGDN", "L_CTRL", "L_WIN", "L_ALT", "SPACE", "R_ALT", "FN", "COPILOT", "LEFT", "DOWN", "RIGHT" };
            for (size_t i = 0; i < 68; ++i) {
                auto it = keymap.GetAllKeys().find(_key_names[i]);
                _keys[i] = it == keymap.GetAllKeys().end() ? nullptr : &it->second;
            }
            _initialized = true; _pc = 3; _wake = 0; _frame.Clear();
            
        }
        _last = elapsed_ms;
        if (elapsed_ms < _wake) { out_frame = _frame; return; }
        const KeyInfo info{};
        for (int _budget = 0; _budget < 4096; ++_budget) {
            switch (_pc) { case 0: { _pc = 3; out_frame = _frame; return;  }
case 1: {         _frame.Fill(ColorRGB{static_cast<uint8_t>(std::clamp(static_cast<double>(0), 0.0, 255.0)), static_cast<uint8_t>(std::clamp(static_cast<double>(150), 0.0, 255.0)), static_cast<uint8_t>(std::clamp(static_cast<double>(255), 0.0, 255.0))});
_pc = 0; break; }
case 2: {         _frame.Fill(ColorRGB{static_cast<uint8_t>(std::clamp(static_cast<double>(255), 0.0, 255.0)), static_cast<uint8_t>(std::clamp(static_cast<double>(0), 0.0, 255.0)), static_cast<uint8_t>(std::clamp(static_cast<double>(0), 0.0, 255.0))});
_pc = 0; break; }
case 3: { _pc = (((gsi ? gsi->GetNumber("player.state.health", 100.0) : 100.0) < 25)) ? 2 : 1; break; } }
        }
        out_frame = _frame;
    
    }
};

} // namespace aura

extern "C" {
    __declspec(dllexport) uint32_t AuraGetPluginApiVersion() {
        return 0x00010000;
    }

    __declspec(dllexport) const char* AuraGetEffectName() {
        return "studio_cs2_health_d6c40fe81cb54d87a84a";
    }

    __declspec(dllexport) aura::Effect* AuraCreateEffect() {
        return new aura::Effect_studio_cs2_health_d6c40fe81cb54d87a84a();
    }

    __declspec(dllexport) void AuraDestroyEffect(aura::Effect* effect) {
        delete effect;
    }
}
