import { normalizePublication } from './publication.js';
import { compileSequence } from './sequenceCompiler.js';
/**
 * C++17 Transpiler for Google Blockly Lighting Effects
 * Emits zero-heap allocation classes conforming to aura::Effect and Aura Plugin ABI v1.0.0.
 */

export class CppTranspiler {
  /**
   * Transpiles a Blockly workspace into full C++17 source code
   * @param {string} effectName 
   * @param {import('blockly').WorkspaceSvg} workspace 
   * @returns {string} C++ source code
   */
  static transpile(effectName, workspace, options = {}) {
    const publication = normalizePublication(options);
    const oneShot = publication.mode === "one_shot";
    const safeName = this.sanitizeIdentifier(effectName);
    const program = compileSequence(workspace, { language: 'cpp', oneShot, value: this.valueToCpp.bind(this), statement: this.blockToCpp.bind(this) });
    const members = (workspace?.getAllVariables?.() || []).map(v => `double var_${v.name.replace(/[^a-zA-Z0-9_]/g, '_')} = 0.0;`).join('\n');
    const resetVars = (workspace?.getAllVariables?.() || []).map(v => `var_${v.name.replace(/[^a-zA-Z0-9_]/g, '_')} = 0.0;`).join('\n');
    const bodyCode = `
        if (!_initialized ${oneShot ? '' : '|| elapsed_ms < _last'}) {
            static constexpr const char* _key_names[68] = { ${program.keyNames} };
            for (size_t i = 0; i < 68; ++i) {
                auto it = keymap.GetAllKeys().find(_key_names[i]);
                _keys[i] = it == keymap.GetAllKeys().end() ? nullptr : &it->second;
            }
            _initialized = true; _pc = ${program.entry}; _wake = 0; _frame.Clear();
            ${resetVars}
        }
        _last = elapsed_ms;
        ${oneShot ? `if (_terminal) {
            if (${publication.fade_out_ms} == 0 || _zero_rendered) _finished = true;
            else {
                _opacity = static_cast<float>(std::clamp(1.0 - static_cast<double>(elapsed_ms - _terminal_at) / ${publication.fade_out_ms || 1}.0, 0.0, 1.0));
                if (_opacity == 0) _zero_rendered = true;
            }
            out_frame = _frame; return;
        }` : ''}
        if (elapsed_ms < _wake) { out_frame = _frame; return; }
        const KeyInfo info{};
        for (int _budget = 0; _budget < 4096; ++_budget) {
            switch (_pc) { ${program.code.replaceAll('out_frame.Fill', '_frame.Fill').replaceAll('out_frame.SetKey', '_frame.SetKey')} }
        }
        out_frame = _frame;
    `;

    return `// Auto-generated by ROG Falchion Ace HFX Blockly Effect Studio
// Target: ISO C++17 / RAII 0-heap allocation
#pragma once

#include "engine/effect.h"
#include "engine/plugin_interface.h"
#include <cmath>
#include <algorithm>
#include <cstdint>
#include <string_view>
#include <string>

namespace aura {

inline ColorRGB LerpRGB(const ColorRGB& a, const ColorRGB& b, double t) {
    const double clamped_t = std::clamp(t, 0.0, 1.0);
    return ColorRGB{
        static_cast<uint8_t>(std::clamp(a.r * (1.0 - clamped_t) + b.r * clamped_t, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(a.g * (1.0 - clamped_t) + b.g * clamped_t, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(a.b * (1.0 - clamped_t) + b.b * clamped_t, 0.0, 255.0))
    };
}

inline ColorRGB ScaleBrightness(const ColorRGB& c, double s) {
    const double factor = std::clamp(s, 0.0, 1.0);
    return ColorRGB{
        static_cast<uint8_t>(std::clamp(c.r * factor, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(c.g * factor, 0.0, 255.0)),
        static_cast<uint8_t>(std::clamp(c.b * factor, 0.0, 255.0))
    };
}

class Effect_${safeName} : public Effect {
public:
    int _pc = ${program.entry};
    double _wake = 0;
    uint64_t _last = 0;
    bool _initialized = false;
    ${oneShot ? 'bool _terminal = false, _finished = false, _zero_rendered = false; uint64_t _terminal_at = 0; float _opacity = 1.0f;' : ''}
    FrameBuffer _frame{};
    const KeyInfo* _keys[68]{};
    int _indices[${program.slots}]{};
    int _limits[${program.slots}]{};
    ${members}
    Effect_${safeName}() = default;
    virtual ~Effect_${safeName}() = default;

    void Render(uint64_t elapsed_ms, FrameBuffer& out_frame, const Keymap& keymap) override {
        RenderInternal(elapsed_ms, out_frame, keymap, nullptr);
    }

    void RenderWithContext(const EffectContext& ctx, FrameBuffer& out_frame) override {
        RenderInternal(ctx.elapsed_ms, out_frame, ctx.keymap, ctx.gsi);
    }

    void RenderInternal(uint64_t elapsed_ms, FrameBuffer& out_frame, const Keymap& keymap, const IGsiReader* gsi) {
${bodyCode}
    }
};

} // namespace aura

extern "C" {
    ${oneShot ? `__declspec(dllexport) uint32_t AURA_PLUGIN_CALL AuraGetEffectLifecycleVersion() { return 1; }
    __declspec(dllexport) uint32_t AURA_PLUGIN_CALL AuraIsEffectFinished(const aura::Effect* effect, uint64_t) {
        return static_cast<const aura::Effect_${safeName}*>(effect)->_finished ? 1 : 0;
    }
    __declspec(dllexport) float AURA_PLUGIN_CALL AuraGetEffectOpacity(const aura::Effect* effect, uint64_t) {
        return static_cast<const aura::Effect_${safeName}*>(effect)->_opacity;
    }` : ''}
    __declspec(dllexport) uint32_t AuraGetPluginApiVersion() {
        return 0x00010000;
    }

    __declspec(dllexport) const char* AuraGetEffectName() {
        return "${safeName}";
    }

    __declspec(dllexport) aura::Effect* AuraCreateEffect() {
        return new aura::Effect_${safeName}();
    }

    __declspec(dllexport) void AuraDestroyEffect(aura::Effect* effect) {
        delete effect;
    }
}
`;
  }

  static sanitizeIdentifier(name) {
    let clean = (name || 'custom_effect').replace(/[^a-zA-Z0-9_]/g, '_');
    if (/^[0-9]/.test(clean)) {
      clean = 'Effect_' + clean;
    }
    return clean;
  }

  /**
   * Traverse the workspace blocks and translate them into C++ statements
   */
  static generateBodyCode(workspace) {
    if (!workspace) return '        // No-op safe pass';
    const topBlocks = workspace.getTopBlocks(true);
    if (!topBlocks || topBlocks.length === 0) {
      return '        out_frame.Fill(0, 0, 0);';
    }

    let statements = [];
    if (workspace && typeof workspace.getAllVariables === 'function') {
      for (const v of workspace.getAllVariables()) {
        const cleanName = v.name.replace(/[^a-zA-Z0-9_]/g, '_');
        statements.push(`        double var_${cleanName} = 0.0;`);
      }
    }

    for (const block of topBlocks) {
      const code = this.blockToCpp(block, '        ');
      if (code) {
        statements.push(code);
      }
    }

    if (statements.length === 0) {
      return '        out_frame.Fill(0, 0, 0);';
    }
    return statements.join('\n');
  }

  static blockToCpp(block, indent = '        ') {
    if (!block) return '';
    const type = block.type;

    switch (type) {
      case 'key_fill_all': {
        const color = this.valueToCpp(block, 'COLOR', 'ColorRGB{255, 128, 0}');
        const next = this.blockToCpp(block.getNextBlock(), indent);
        return `${indent}out_frame.Fill(${color});${next ? '\n' + next : ''}`;
      }

      case 'key_set_color': {
        const ledId = this.valueToCpp(block, 'LED_ID', 'info.led_id');
        const color = this.valueToCpp(block, 'COLOR', 'ColorRGB{255, 255, 255}');
        const next = this.blockToCpp(block.getNextBlock(), indent);
        return `${indent}out_frame.SetKey(static_cast<size_t>(${ledId}), ${color});${next ? '\n' + next : ''}`;
      }

      case 'key_ripple_effect': {
        const centerKey = block.getFieldValue('KEY') || 'W';
        const color = this.valueToCpp(block, 'COLOR', 'ColorRGB{0, 200, 255}');
        const speed = parseFloat(block.getFieldValue('SPEED') || '2.5') || 2.5;
        const next = this.blockToCpp(block.getNextBlock(), indent);
        return `${indent}{\n` +
               `${indent}    double _cx = 7.5, _cy = 3.0;\n` +
               `${indent}    auto _it = keymap.GetAllKeys().find("${centerKey}");\n` +
               `${indent}    if (_it != keymap.GetAllKeys().end()) { _cx = _it->second.physical_x; _cy = _it->second.physical_y; }\n` +
               `${indent}    const ColorRGB _base_col = ${color};\n` +
               `${indent}    const double _sp = ${speed};\n` +
               `${indent}    for (size_t _i = 0; _i < 68; ++_i) {\n` +
               `${indent}        if (!_keys[_i]) continue;\n` +
               `${indent}        const double _dist = std::hypot(_keys[_i]->physical_x - _cx, _keys[_i]->physical_y - _cy);\n` +
               `${indent}        const double _phase = std::fmod(std::fmod(_dist - (static_cast<double>(elapsed_ms) / 1000.0) * _sp, 4.0) + 4.0, 4.0);\n` +
               `${indent}        const double _wave = std::max(0.0, 1.0 - std::fabs(_phase - 1.0));\n` +
               `${indent}        out_frame.SetKey(_i, ScaleBrightness(_base_col, _wave));\n` +
               `${indent}    }\n` +
               `${indent}}${next ? '\n' + next : ''}`;
      }

      case 'key_for_each': {
        const zone = block.getFieldValue('ZONE') || 'all';
        const doBlock = block.getInputTargetBlock('DO');
        const doCode = doBlock ? this.blockToCpp(doBlock, indent + '    ') : '';
        const next = this.blockToCpp(block.getNextBlock(), indent);

        let filterCondition = '';
        if (zone === 'wasd') {
          filterCondition = 'if (name == "W" || name == "A" || name == "S" || name == "D") ';
        } else if (zone === 'arrows') {
          filterCondition = 'if (name == "UP" || name == "DOWN" || name == "LEFT" || name == "RIGHT") ';
        } else if (zone === 'numeric') {
          filterCondition = 'if (info.physical_row == 1 && info.physical_col >= 2 && info.physical_col <= 13) ';
        } else if (zone === 'navigation') {
          filterCondition = 'if (info.physical_col >= 14 || name == "UP" || name == "DOWN" || name == "LEFT" || name == "RIGHT") ';
        } else if (zone === 'modifier') {
          filterCondition = 'if (name == "L_CTRL" || name == "R_CTRL" || name == "LCTRL" || name == "RCTRL" || name == "L_SHIFT" || name == "R_SHIFT" || name == "LSHIFT" || name == "RSHIFT" || name == "L_ALT" || name == "R_ALT" || name == "LALT" || name == "RALT" || name == "TAB" || name == "CAPS" || name == "ENTER") ';
        }

        return `${indent}for (const auto& [name, info] : keymap.GetAllKeys()) {\n` +
               (filterCondition ? `${indent}    ${filterCondition}{\n${doCode}\n${indent}    }\n` : `${doCode}\n`) +
               `${indent}}${next ? '\n' + next : ''}`;
      }

      case 'controls_if': {
        let code = '';
        let i = 0;
        while (block.getInput(`IF${i}`)) {
          const cond = this.valueToCpp(block, `IF${i}`, 'false');
          const doBlock = block.getInputTargetBlock(`DO${i}`);
          const doCode = doBlock ? this.blockToCpp(doBlock, indent + '    ') : '';
          if (i === 0) {
            code += `${indent}if (${cond}) {\n${doCode}\n${indent}}`;
          } else {
            code += ` else if (${cond}) {\n${doCode}\n${indent}}`;
          }
          i++;
        }
        const elseBlock = block.getInputTargetBlock('ELSE');
        if (elseBlock) {
          const elseCode = this.blockToCpp(elseBlock, indent + '    ');
          code += ` else {\n${elseCode}\n${indent}}`;
        }
        const next = this.blockToCpp(block.getNextBlock(), indent);
        return `${code}${next ? '\n' + next : ''}`;
      }

      case 'controls_repeat_ext': {
        const times = this.valueToCpp(block, 'TIMES', '10');
        const doBlock = block.getInputTargetBlock('DO');
        const doCode = doBlock ? this.blockToCpp(doBlock, indent + '    ') : '';
        const next = this.blockToCpp(block.getNextBlock(), indent);
        return `${indent}for (int _rpt = 0; _rpt < std::min(1000, std::max(0, static_cast<int>(${times}))); ++_rpt) {\n${doCode}\n${indent}}${next ? '\n' + next : ''}`;
      }

      case 'controls_whileUntil': {
        const mode = block.getFieldValue('MODE') || 'WHILE';
        let cond = this.valueToCpp(block, 'BOOL', 'false');
        if (mode === 'UNTIL') cond = `!(${cond})`;
        const doBlock = block.getInputTargetBlock('DO');
        const doCode = doBlock ? this.blockToCpp(doBlock, indent + '    ') : '';
        const next = this.blockToCpp(block.getNextBlock(), indent);
        return `${indent}{\n` +
               `${indent}    int _loop_guard = 0;\n` +
               `${indent}    while (${cond}) {\n` +
               `${indent}        if (++_loop_guard > 10000) break;\n` +
               `${doCode}\n` +
               `${indent}    }\n` +
               `${indent}}${next ? '\n' + next : ''}`;
      }

      case 'controls_flow_statements': {
        const flow = block.getFieldValue('FLOW') || 'BREAK';
        return `${indent}${flow === 'BREAK' ? 'break;' : 'continue;'}\n`;
      }

      case 'effect_wait_ms': {
        const next = this.blockToCpp(block.getNextBlock(), indent);
        return next;
      }

      case 'variables_set': {
        const varModel = block.getField('VAR')?.getVariable?.();
        const varName = varModel ? varModel.name : (block.getFieldValue('VAR') || 'x');
        const cleanName = varName.replace(/[^a-zA-Z0-9_]/g, '_');
        const val = this.valueToCpp(block, 'VALUE', '0.0');
        const next = this.blockToCpp(block.getNextBlock(), indent);
        return `${indent}var_${cleanName} = static_cast<double>(${val});${next ? '\n' + next : ''}`;
      }

      case 'math_change': {
        const varModel = block.getField('VAR')?.getVariable?.();
        const varName = varModel ? varModel.name : (block.getFieldValue('VAR') || 'x');
        const cleanName = varName.replace(/[^a-zA-Z0-9_]/g, '_');
        const delta = this.valueToCpp(block, 'DELTA', '1.0');
        const next = this.blockToCpp(block.getNextBlock(), indent);
        return `${indent}var_${cleanName} += static_cast<double>(${delta});${next ? '\n' + next : ''}`;
      }

      default: {
        const next = this.blockToCpp(block.getNextBlock(), indent);
        return next;
      }
    }
  }

  static valueToCpp(block, inputName, fallback = '0.0') {
    const target = block.getInputTargetBlock(inputName);
    if (!target) return fallback;

    switch (target.type) {
      case 'math_number':
        return target.getFieldValue('NUM') || '0';

      case 'time_elapsed_ms':
        return 'static_cast<double>(elapsed_ms)';

      case 'time_phase': {
        const period = this.valueToCpp(target, 'PERIOD', '2000.0');
        return `(std::fmod(static_cast<double>(elapsed_ms), std::max(33.0, static_cast<double>(${period}))) / std::max(33.0, static_cast<double>(${period})))`;
      }

      case 'math_waveform': {
        const wType = target.getFieldValue('TYPE') || 'SINE';
        const phase = this.valueToCpp(target, 'PHASE', '0.0');
        const amp = this.valueToCpp(target, 'AMPLITUDE', '1.0');
        const offset = this.valueToCpp(target, 'OFFSET', '0.0');

        if (wType === 'SINE') {
          return `(std::sin(static_cast<double>(${phase}) * 6.283185307179586) * ${amp} + ${offset})`;
        } else if (wType === 'TRIANGLE') {
          return `((std::fabs(std::fmod(static_cast<double>(${phase}), 1.0) * 2.0 - 1.0) * 2.0 - 1.0) * ${amp} + ${offset})`;
        } else if (wType === 'SQUARE') {
          return `((std::fmod(static_cast<double>(${phase}), 1.0) < 0.5 ? 1.0 : -1.0) * ${amp} + ${offset})`;
        } else {
          return `((std::fmod(static_cast<double>(${phase}), 1.0) * 2.0 - 1.0) * ${amp} + ${offset})`;
        }
      }

      case 'geometry_coords': {
        const field = target.getFieldValue('FIELD') || 'physical_x';
        if (field === 'row') return 'info.physical_row';
        if (field === 'col') return 'info.physical_col';
        return `info.${field}`;
      }

      case 'geometry_distance': {
        const x1 = this.valueToCpp(target, 'X1', '0.0');
        const y1 = this.valueToCpp(target, 'Y1', '0.0');
        const x2 = this.valueToCpp(target, 'X2', '0.0');
        const y2 = this.valueToCpp(target, 'Y2', '0.0');
        return `std::sqrt((${x1} - ${x2}) * (${x1} - ${x2}) + (${y1} - ${y2}) * (${y1} - ${y2}))`;
      }

      case 'geometry_radial_phase': {
        const cx = this.valueToCpp(target, 'CX', '7.5');
        const cy = this.valueToCpp(target, 'CY', '3.0');
        const wl = this.valueToCpp(target, 'WAVELENGTH', '4.0');
        const sp = this.valueToCpp(target, 'SPEED', '2.0');
        return `std::fmod(std::sqrt((info.physical_x - ${cx})*(info.physical_x - ${cx}) + (info.physical_y - ${cy})*(info.physical_y - ${cy})) / std::max(0.1, static_cast<double>(${wl})) - (static_cast<double>(elapsed_ms) / 1000.0) * ${sp}, 1.0)`;
      }

      case 'color_rgb': {
        const r = this.valueToCpp(target, 'R', '255');
        const g = this.valueToCpp(target, 'G', '0');
        const b = this.valueToCpp(target, 'B', '0');
        return `ColorRGB{static_cast<uint8_t>(std::clamp(static_cast<double>(${r}), 0.0, 255.0)), static_cast<uint8_t>(std::clamp(static_cast<double>(${g}), 0.0, 255.0)), static_cast<uint8_t>(std::clamp(static_cast<double>(${b}), 0.0, 255.0))}`;
      }

      case 'color_hsv': {
        const h = this.valueToCpp(target, 'H', '0');
        const s = this.valueToCpp(target, 'S', '100');
        const v = this.valueToCpp(target, 'V', '100');
        return `[&]() -> ColorRGB {
            double h_norm = std::fmod(static_cast<double>(${h}), 360.0);
            if (h_norm < 0.0) h_norm += 360.0;
            double s_norm = std::clamp(static_cast<double>(${s}) / 100.0, 0.0, 1.0);
            double v_norm = std::clamp(static_cast<double>(${v}) / 100.0, 0.0, 1.0);
            double c = v_norm * s_norm;
            double x = c * (1.0 - std::fabs(std::fmod(h_norm / 60.0, 2.0) - 1.0));
            double m = v_norm - c;
            double r1 = 0, g1 = 0, b1 = 0;
            if (h_norm < 60) { r1 = c; g1 = x; b1 = 0; }
            else if (h_norm < 120) { r1 = x; g1 = c; b1 = 0; }
            else if (h_norm < 180) { r1 = 0; g1 = c; b1 = x; }
            else if (h_norm < 240) { r1 = 0; g1 = x; b1 = c; }
            else if (h_norm < 300) { r1 = x; g1 = 0; b1 = c; }
            else { r1 = c; g1 = 0; b1 = x; }
            return ColorRGB{
                static_cast<uint8_t>(std::clamp((r1 + m) * 255.0, 0.0, 255.0)),
                static_cast<uint8_t>(std::clamp((g1 + m) * 255.0, 0.0, 255.0)),
                static_cast<uint8_t>(std::clamp((b1 + m) * 255.0, 0.0, 255.0))
            };
        }()`;
      }

      case 'color_lerp': {
        const ca = this.valueToCpp(target, 'COLOR_A', 'ColorRGB{0, 0, 0}');
        const cb = this.valueToCpp(target, 'COLOR_B', 'ColorRGB{255, 255, 255}');
        const ratio = this.valueToCpp(target, 'RATIO', '0.5');
        return `LerpRGB(${ca}, ${cb}, ${ratio})`;
      }

      case 'color_brightness': {
        const c = this.valueToCpp(target, 'COLOR', 'ColorRGB{255, 255, 255}');
        const scale = this.valueToCpp(target, 'SCALE', '1.0');
        return `ScaleBrightness(${c}, ${scale})`;
      }

      case 'color_cycle': {
        const ca = this.valueToCpp(target, 'COLOR_A', 'ColorRGB{0, 180, 255}');
        const cb = this.valueToCpp(target, 'COLOR_B', 'ColorRGB{255, 0, 128}');
        const periodSec = this.valueToCpp(target, 'PERIOD_SEC', '2.0');
        return `[&]() -> ColorRGB {
            const double _p_ms = std::max(100.0, static_cast<double>(${periodSec}) * 1000.0);
            const double _phase = std::fmod(static_cast<double>(elapsed_ms), _p_ms) / _p_ms;
            const double _ratio = 0.5 - 0.5 * std::cos(_phase * 6.283185307179586);
            return LerpRGB(${ca}, ${cb}, _ratio);
        }()`;
      }

      case 'key_is_pressed':
        return 'false';

      case 'key_decay':
        return '0.0';

      case 'text':
        return JSON.stringify(target.getFieldValue('TEXT') || '');

      case 'logic_boolean':
        return (target.getFieldValue('BOOL') === 'TRUE') ? 'true' : 'false';

      case 'logic_negate':
        return `(!${this.valueToCpp(target, 'BOOL', 'false')})`;

      case 'logic_operation': {
        const op = target.getFieldValue('OP') || 'AND';
        const a = this.valueToCpp(target, 'A', 'true');
        const b = this.valueToCpp(target, 'B', 'true');
        return `(${a} ${op === 'OR' ? '||' : '&&'} ${b})`;
      }

      case 'gsi_state_match': {
        const stateKey = target.getFieldValue('STATE') || 'round.bomb';
        const op = target.getFieldValue('OP') || '==';
        const expectedVal = target.getFieldValue('VALUE') || '';
        const opSym = op === '!=' ? '!=' : '==';
        return `(std::string_view(gsi ? gsi->GetString("${stateKey}", "") : "") ${opSym} ${JSON.stringify(expectedVal)})`;
      }

      case 'gsi_numeric_compare': {
        const fieldKey = target.getFieldValue('FIELD') || 'player.state.health';
        const op = target.getFieldValue('OP') || '<';
        const rawVal = target.getFieldValue('VALUE');
        const expectedNum = (rawVal !== null && rawVal !== undefined && !isNaN(Number(rawVal))) ? Number(rawVal) : 0.0;
        let opSym = '==';
        if (op === '<') opSym = '<';
        else if (op === '<=') opSym = '<=';
        else if (op === '>') opSym = '>';
        else if (op === '>=') opSym = '>=';
        else if (op === '!=') opSym = '!=';
        return `((gsi ? gsi->GetNumber("${fieldKey}", 0.0) : 0.0) ${opSym} ${expectedNum})`;
      }

      case 'gsi_player_health_condition': {
        const op = target.getFieldValue('OP') || '<';
        const rawVal = target.getFieldValue('VALUE');
        const expectedNum = (rawVal !== null && rawVal !== undefined && !isNaN(Number(rawVal))) ? Number(rawVal) : 25.0;
        let opSym = '<';
        if (op === '<=') opSym = '<=';
        else if (op === '>') opSym = '>';
        else if (op === '>=') opSym = '>=';
        else if (op === '==') opSym = '==';
        return `((gsi ? gsi->GetNumber("player.state.health", 100.0) : 100.0) ${opSym} ${expectedNum})`;
      }

      case 'gsi_c4_state_condition': {
        const expectedVal = target.getFieldValue('STATE') || 'planted';
        return `(std::string_view(gsi ? gsi->GetString("round.bomb", "") : "") == ${JSON.stringify(expectedVal)})`;
      }

      case 'gsi_enum_constant': {
        const val = target.getFieldValue('VALUE') || '';
        return JSON.stringify(val);
      }

      case 'gsi_get_number': {
        const path = target.getFieldValue('PATH') || 'player.state.health';
        const def = this.valueToCpp(target, 'DEFAULT', '100.0');
        return `(gsi ? gsi->GetNumber("${path}", ${def}) : ${def})`;
      }

      case 'gsi_get_string': {
        const path = target.getFieldValue('PATH') || 'round.bomb';
        const def = this.valueToCpp(target, 'DEFAULT', '""');
        return `(gsi ? gsi->GetString("${path}", ${def}) : ${def})`;
      }

      case 'gsi_get_boolean': {
        const path = target.getFieldValue('PATH') || 'player.state.helmet';
        const def = this.valueToCpp(target, 'DEFAULT', 'false');
        return `(gsi ? gsi->GetBool("${path}", ${def}) : ${def})`;
      }

      case 'math_arithmetic': {
        const op = target.getFieldValue('OP') || 'ADD';
        const a = this.valueToCpp(target, 'A', '0.0');
        const b = this.valueToCpp(target, 'B', '0.0');
        let opSym = '+';
        if (op === 'MINUS') opSym = '-';
        else if (op === 'MULTIPLY') opSym = '*';
        else if (op === 'DIVIDE') opSym = '/';
        return `(${a} ${opSym} ${b})`;
      }

      case 'logic_compare': {
        const op = target.getFieldValue('OP') || 'EQ';
        const a = this.valueToCpp(target, 'A', '0.0');
        const b = this.valueToCpp(target, 'B', '0.0');
        let opSym = '==';
        if (op === 'NEQ') opSym = '!=';
        else if (op === 'LT') opSym = '<';
        else if (op === 'LTE') opSym = '<=';
        else if (op === 'GT') opSym = '>';
        else if (op === 'GTE') opSym = '>=';
        return `(${a} ${opSym} ${b})`;
      }

      case 'variables_get': {
        const varModel = target.getField('VAR')?.getVariable?.();
        const varName = varModel ? varModel.name : (target.getFieldValue('VAR') || 'x');
        const cleanName = varName.replace(/[^a-zA-Z0-9_]/g, '_');
        return `var_${cleanName}`;
      }

      case 'math_single': {
        const op = target.getFieldValue('OP') || 'ROOT';
        const num = this.valueToCpp(target, 'NUM', '0.0');
        if (op === 'ROOT') return `std::sqrt(static_cast<double>(${num}))`;
        if (op === 'ABS') return `std::fabs(static_cast<double>(${num}))`;
        if (op === 'NEG') return `(-static_cast<double>(${num}))`;
        if (op === 'LN') return `std::log(static_cast<double>(${num}))`;
        if (op === 'LOG10') return `std::log10(static_cast<double>(${num}))`;
        if (op === 'EXP') return `std::exp(static_cast<double>(${num}))`;
        if (op === 'POW10') return `std::pow(10.0, static_cast<double>(${num}))`;
        return num;
      }

      case 'math_trig': {
        const op = target.getFieldValue('OP') || 'SIN';
        const num = this.valueToCpp(target, 'NUM', '0.0');
        if (op === 'SIN') return `std::sin(static_cast<double>(${num}))`;
        if (op === 'COS') return `std::cos(static_cast<double>(${num}))`;
        if (op === 'TAN') return `std::tan(static_cast<double>(${num}))`;
        if (op === 'ASIN') return `std::asin(static_cast<double>(${num}))`;
        if (op === 'ACOS') return `std::acos(static_cast<double>(${num}))`;
        if (op === 'ATAN') return `std::atan(static_cast<double>(${num}))`;
        return num;
      }

      case 'math_round': {
        const op = target.getFieldValue('OP') || 'ROUND';
        const num = this.valueToCpp(target, 'NUM', '0.0');
        if (op === 'ROUND') return `std::round(static_cast<double>(${num}))`;
        if (op === 'ROUNDUP') return `std::ceil(static_cast<double>(${num}))`;
        if (op === 'ROUNDDOWN') return `std::floor(static_cast<double>(${num}))`;
        return num;
      }

      case 'math_modulo': {
        const a = this.valueToCpp(target, 'DIVIDEND', '0.0');
        const b = this.valueToCpp(target, 'DIVISOR', '1.0');
        return `std::fmod(static_cast<double>(${a}), static_cast<double>(${b}))`;
      }

      default:
        return fallback;
    }
  }

  /**
   * Verify zero heap allocations inside Render
   */
  static checkZeroAllocations(source) {
    const forbidden = [
      { regex: /\bnew\s+\w+/, msg: "Forbidden 'new' operator inside Render loop" },
      { regex: /\bmalloc\s*\(/, msg: "Forbidden 'malloc' inside Render loop" },
      { regex: /\bcalloc\s*\(/, msg: "Forbidden 'calloc' inside Render loop" },
      { regex: /\bpush_back\s*\(/, msg: "Forbidden 'push_back' dynamic vector growth inside Render loop" },
      { regex: /\bstd::string\s+\w+\s*=\s*\w+\s*\+/, msg: "Forbidden heap std::string concatenation" },
      { regex: /\bstd::stringstream\b/, msg: "Forbidden dynamic stream allocation inside Render loop" }
    ];

    const violations = [];
    for (const rule of forbidden) {
      if (rule.regex.test(source)) {
        violations.push(rule.msg);
      }
    }
    return { ok: violations.length === 0, violations };
  }
}
